#ifndef __ZB_DEFS_H__
#define __ZB_DEFS_H__

//#define DEVICE_PROFILE_ID ESP_ZB_AF_HA_PROFILE_ID

#define MAX_DEVICE_ENDPOINTS 20
#define MAX_ENDPOINT_CLUSTERS 6
#define MAX_CLUSTER_ATTRIBUTES 10

#define NVS_APP_VERSION 0x0118

#define USE_BASIC_CLUSTER
#define USE_POWER_CONFIG_CLUSTER
#define USE_DEVICE_TEMP_CONFIG_CLUSTER
#define USE_IDENTIFY_CLUSTER
#define USE_GROUPS_CLUSTER
#define USE_SCENES_CLUSTER
#define USE_ON_OFF_CLUSTER
#define USE_ON_OFF_SWITCH_CONFIG_CLUSTER
#define USE_LEVEL_CLUSTER
#define USE_ALARMS_CLUSTER
#define USE_TIME_CLUSTER
#define USE_RSSI_LOCATION_CLUSTER
#define USE_ANALOG_INPUT_CLUSTER
#define USE_ANALOG_OUTPUT_CLUSTER
#define USE_ANALOG_VALUE_CLUSTER
#define USE_BINARY_INPUT_CLUSTER
#define USE_BINARY_OUTPUT_CLUSTER
#define USE_BINARY_VALUE_CLUSTER
#define USE_MULTI_INPUT_CLUSTER
#define USE_MULTI_OUTPUT_CLUSTER
#define USE_MULTI_VALUE_CLUSTER
#define USE_COMMISSIONING_CLUSTER
#define USE_OTA_UPGRADE_CLUSTER
#define USE_POLL_CONTROL_CLUSTER
#define USE_GREEN_POWER_CLUSTER
#define USE_KEEP_ALIVE_CLUSTER
#define USE_SHADE_CONFIG_CLUSTER
#define USE_DOOR_LOCK_CLUSTER
#define USE_WINDOW_COVERING_CLUSTER
#define USE_CONFIG_CONTROL_CLUSTER
#define USE_THERMOSTAT_CLUSTER
#define USE_FAN_CONTROL_CLUSTER
#define USE_THERMOSTAT_UI_CONFIG_CLUSTER
#define USE_COLOR_CONTROL_CLUSTER
#define USE_BALLAST_CONFIG_CLUSTER
#define USE_ILLUMINANCE_MEASUREMENT_CLUSTER
#define USE_TEMPERATURE_MEASUREMENT_CLUSTER
#define USE_PRESSURE_MEASUREMENT_CLUSTER
#define USE_HUMIDITY_MEASUREMENT_CLUSTER
#define USE_OCCUPANCY_SENSING_CLUSTER
#define USE_CARBON_DIOXIDE_MEASUREMENT_CLUSTER
#define USE_PM2_5_MEASUREMENT_CLUSTER
#define USE_IAS_ZONE_CLUSTER
#define USE_ELECTRICAL_MEAS_CLUSTER
#define USE_METERING_CLUSTER

//uint8_t extpanId[8] = {0xDD, 0xDD, 0xDD, 0xDD, 0xDD, 0xDD, 0xDD, 0xDD};
//uint8_t networkKey[16] = {1, 3, 5, 7, 9, 11, 13, 15, 0, 2, 4, 6, 8, 10, 12, 13};

#endif //__ZB_DEFS_H__